### DISCUSSION TITLE
tutorials/voyage-part1/14-putting-it-all-together

### DISCUSSION THREAD

**Discussion by giscus** [apollographql-education/content-feedback#165] [course feedback]
# tutorials/voyage-part1/14-putting-it-all-together

Now that your backend is finished, run the frontend application to see how everything fits together!

https://www.apollographql.com/tutorials/voyage-part1/14-putting-it-all-together

**Comment by kid1412621** [comment]
for those installed the latest version of Apollo router, use this config:
```yaml
cors:
  policies:
    - origins:
        - http://localhost:3000 # Allows any locally-running client to run against your Router
        - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
```
